# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

shared:
  mailer:
    address: <%= ENV["MAILER_ADDRESS"] || "" %>
    domain: <%= ENV["MAILER_DOMAIN"] || "" %>
    username: <%= ENV["MAILER_USERNAME"] || "" %>
    password: <%= ENV["MAILER_PASSWORD"] || "" %>
    host: <%= ENV["MAILER_HOST"] || "" %>

development:
  secret_key_base: 1b82622437896f581d73ddf8704b6437acf0a62ace34933d2c28eb72fbb402e72f3d1200c3c0b94742648680990eaa056e737b4562e7ba4f75d5cb6a53041117

test:
  secret_key_base: 0942ab60061f29d6d29700428680b207ed67a0ae9bf7b026e30a6478a4deebc1bf65fccd939b1c5cf64ada997dd61cfa5d8c84d4ae0760e52ae8bb6dd3d9548b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
